### ISSUE TITLE
Not working for Nifty and Bank Nifty

### ISSUE THREAD

**Issue by aaryan-verma** [pratik141/nsedt#20]
Returns an empty data frame when given an input "NIFTY 50" OR "NIFTY50" OR "BANK NIFTY" OR "BANKNIFTY" OR "NIFTY BANK" OR "NIFTYBANK"

**Comment by pratik141** [comment]
Which version you are using ?

it worked for me
>>> from datetime import date
>>> from nsedt import indices as ind
>>> start_date = date(2023, 1, 1)
>>> end_date = date(2023, 2, 2)
>>> print(ind.get_price(start_date, end_date, symbol="NIFTY 50", response_type="panda_df"))
    Open Price  High Price  Close Price  Low Price                      Date  Total Traded Quantity  Total Traded Value
0     18131.70    18215.15     18197.45   18086.50  2023-01-01T18:30:00.000Z              256073979            11793.06
1     18163.20    18251.95     18232.55   18149.80  2023-01-02T18:30:00.000Z              208699772            13680.91
2     18230.65    18243.00     18042.95   18020.60  2023-01-03T18:30:00.000Z              235162202            16687.71
3     18101.95    18120.30     17992.15   17892.60  2023-01-04T18:30:00.000Z              269949738            22108.53
>>> 
>>> 
>>> print(ind.get_price(start_date, end_date, symbol="NIFTY BANK", response_type="panda_df"))
    Open Price  High Price  Close Price  Low Price                      Date  Total Traded Quantity  Total Traded Value
0     43038.25    43382.75     43203.10   42961.75  2023-01-01T18:30:00.000Z              179810215             3452.51
1     43151.45    43482.80     43425.25   43148.45  2023-01-02T18:30:00.000Z              197035356             4510.22
2     43417.50    43578.40     42958.80   42858.65  2023-01-03T18:30:00.000Z              216794117             6213.83
3     43073.05    43137.55     42608.70   42298.60  2023-01-04T18:30:00.000Z              189076453             5545.57

**Comment by aaryan-verma** [comment]
Thanks. I didn't know the use of 'ind'
Is there any documentation that I can refer ?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
07/05/23,
11:57:07 AM

**Comment by pratik141** [comment]
I will add it soon
