### ISSUE TITLE
Getting Wrong Close Price for POWERGRID stock, ex : 2023-09-11 - value 264.5/- but in google 52wk High is 205/-

### ISSUE THREAD

**Issue by itsmyownview** [pratik141/nsedt#35]
**Describe the bug**
Wrong Close Price for stock POWERGRID - NSE, for multiple dates in Sep 2023. Its w2wk high is only 204, but we are getting > 260 multiple days in Sep 2023

**To Reproduce**
1. install nsedt 0.0.10
2. Try to fetch data for ("POWERGRID", "01-09-2023", "19-09-2023")

**Expected behavior**
Correct value is returned for Close Price

**Screenshots**
Below screenshot is from our library while fetching ("POWERGRID", "01-09-2023", "19-09-2023")

<img width="782" alt="image" src="https://github.com/pratik141/nsedt/assets/75475457/f2b50ee3-be35-44d6-a2b1-75970845f280">

Below screenshot is from google, which says POWERGRID never went above 260 in last 1 year.

<img width="525" alt="image" src="https://github.com/pratik141/nsedt/assets/75475457/67ac18a2-c66a-4cdf-9065-d9f0ef99f4c9">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: windows

**Comment by pratik141** [comment]
Hi @itsmyownview 

there is Bonus 1:3  issued in Powergrid on 12-Sep-2023 and nseindia doesn't adjust the price we have to do it our own 
In future, I will add this option 


<img width="845" alt="image" src="https://github.com/pratik141/nsedt/assets/13189088/e809f795-78f6-43e4-9cc5-d6c5d6bf0e8e">

**Comment by itsmyownview** [comment]
Please keep us updated with this and how to adjust the price in these cases so that still we are getting correct close price.
Thanks much for your fast response (y)
