### ISSUE TITLE
nsedt library returns empty data whereas nseindia url return valid value

### ISSUE THREAD

**Issue by itsmyownview** [pratik141/nsedt#39]
**Describe the bug**
Sometimes, mostly right after the day closure of nse, when i try to run nsedt library to see Close Price, I can see empty dataframe returned. 

**To Reproduce**

https://www.nseindia.com/api/quote-equity?symbol=SBIN returns correct data, but not nsedt lib.
Time of Execution : 

2023-10-09 16:31:15 IST
2023-10-09 13:01:15 CET

Name: nsedt
Version: 0.0.10

Please check the uploaded screenshots.

**Expected behavior**
Correct dataframe is returned instead of empty dataframe.
I hope there is any time constraints to execute nsedt ?

**Screenshots**
Valid response from nseindia
<img width="949" alt="valid_value_from_nseindia" src="https://github.com/pratik141/nsedt/assets/75475457/ff3f8d2a-8649-4513-bafc-531f3af32298">

Empty dataframe from nsedt

<img width="809" alt="Empty_Dataframe_From_nsedt" src="https://github.com/pratik141/nsedt/assets/75475457/fbc19a9d-b140-482d-a849-a2d81930f249">

**Comment by pratik141** [comment]
I will add these point in doc

**Comment by pratik141** [comment]
closing this issue please feel free to re-open or create a new issue
