### ISSUE TITLE
Wrong Close Price for NSE stocks compared to NSE India, Google or TradingView in nsedt library

### ISSUE THREAD

**Issue by itsmyownview** [pratik141/nsedt#40]
**Describe the bug**
nsedt is giving wrong Close Price w.r.to NSE India, Google or TradingView. After NSE hours, say 4:00 PM CET, when we are checking all 3 - NSE India / Google / TradingView have same value, but when we fetch same stock value via nsedt, it gives some other value.

**To Reproduce**
Please refer screenshot attached.

Name: nsedt
Version: 0.0.10

**Expected behavior**
nsedt should give same value as nseindia/google.

**Screenshots**

I did an analysis on 9th Oct 2023 for 5 stocks. All 5 had incorrect Close Price for nsedt but same for NSE India/Google/TradingView.

<img width="374" alt="image" src="https://github.com/pratik141/nsedt/assets/75475457/093e14a4-fcc6-45ee-a98c-2857b32c1799">

Incorrect value from nsedt library - 3638.35

<img width="620" alt="tcs_incorrect_nsedt" src="https://github.com/pratik141/nsedt/assets/75475457/6ed8a848-56dd-4bde-9a35-afbd09e7fe53">

Correct value from NSE India

<img width="955" alt="close_price_correct_nseindia" src="https://github.com/pratik141/nsedt/assets/75475457/eec945a5-80b8-49e4-aa39-7008c58537da">

Correct Close Price from Google

<img width="955" alt="tcs_correct_google" src="https://github.com/pratik141/nsedt/assets/75475457/5cdda5cd-1755-4b81-9769-f0a9dc3f12eb">

Correct Close Price from TradingView

<img width="958" alt="tcs_correct_tradingview" src="https://github.com/pratik141/nsedt/assets/75475457/8ce06939-4174-4e04-bce0-cc370478f499">

**Comment by pratik141** [comment]
Hi @itsmyownview  
The price you receive from Google/nseindia is the `LAST_TRADED_PRICE` (as of @15:30 IST), whereas the price from nsedt lib is the closing price following all adjustments.

<img width="296" alt="image" src="https://github.com/pratik141/nsedt/assets/13189088/f057c6c0-2e5a-4dbf-9cdf-f340c0911461">
<img width="898" alt="image" src="https://github.com/pratik141/nsedt/assets/13189088/9d99b066-7666-4803-8bbb-24948107008f">

In the upcoming release, I'll include the option for custom columns as well as LTP columns.
