### ISSUE TITLE
Dynamic headers for making API calls to NSE

### ISSUE THREAD

**Issue by jitendravarma** [pratik141/nsedt#51]
Right now I see that we have fixed headers for making api requests to NSE. Problem with this is, if many users are requesting the NSE api, then NSE blocks the given headers. So no new reqports file will be downloaded for same headers.

Solution that I like to propose it, to use python  header faker library to mock headers and then shoot request. That way all different users will have their own set of headers and wont get blocked.

Library: https://pypi.org/project/fake-headers/

**Comment by pratik141** [comment]
Good suggestion 

> Library: https://pypi.org/project/fake-headers/
This library is in a stale state.
Need to find a different one.

or I will add some random headers

**Comment by jitendravarma** [comment]
Added working fake headers logic to the get_headers function.

**Comment by pratik141** [comment]
Link #50

**Comment by pratik141** [comment]
Some warning are coming in py 3.11 need to fix later
